run-dist:
		./build/install/app/bin/app
build:
	./gradlew clean build
run-install:
	./gradlew clean install
run:
	./gradlew run
test:
	./gradlew test
report:
	./gradlew jacocoTestReport
lint:
	./gradlew checkstyleMain
.PHONY: build